# Generated by Django 5.2.17 on 2026-08-20 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0002_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFLTeamGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_for', models.PositiveSmallIntegerField(default=0)),
                ('points_allowed', models.PositiveSmallIntegerField(default=0)),
                ('offensive_passing_yards', models.IntegerField(default=0)),
                ('passing_attempts', models.PositiveSmallIntegerField(default=0)),
                ('passing_completions', models.PositiveSmallIntegerField(default=0)),
                ('offensive_rushing_yards', models.IntegerField(default=0)),
                ('rushing_attempts', models.PositiveSmallIntegerField(default=0)),
                ('sacks_allowed', models.PositiveSmallIntegerField(default=0)),
                ('first_downs', models.PositiveSmallIntegerField(default=0)),
                ('third_down_attempts', models.PositiveSmallIntegerField(default=0)),
                ('third_down_conversions', models.PositiveSmallIntegerField(default=0)),
                ('fourth_down_attempts', models.PositiveSmallIntegerField(default=0)),
                ('fourth_down_conversions', models.PositiveSmallIntegerField(default=0)),
                ('penalties', models.PositiveSmallIntegerField(default=0)),
                ('penalty_yards', models.PositiveSmallIntegerField(default=0)),
                ('offensive_turnovers', models.PositiveSmallIntegerField(default=0)),
                ('defensive_sacks', models.PositiveSmallIntegerField(default=0)),
                ('defensive_passing_yards_allowed', models.IntegerField(default=0)),
                ('defensive_rushing_yards_allowed', models.IntegerField(default=0)),
                ('defensive_turnovers_forced', models.PositiveSmallIntegerField(default=0)),
                ('field_goals_made', models.PositiveSmallIntegerField(default=0)),
                ('field_goals_attempted', models.PositiveSmallIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfl_team_stats', to='games.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfl_game_stats', to='teams.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game', 'team'), name='unique_nfl_team_stats_per_game')],
            },
        ),
    ]
