# Generated by Django 5.2.17 on 2026-08-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflteamgamestats',
            name='defensive_qb_hits',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nflteamgamestats',
            name='defensive_tackles_for_loss',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nflteamgamestats',
            name='passing_air_yards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nflteamgamestats',
            name='passing_cpoe',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nflteamgamestats',
            name='passing_epa',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nflteamgamestats',
            name='passing_yards_after_catch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nflteamgamestats',
            name='rushing_epa',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='defensive_sacks',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='first_downs',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='fourth_down_attempts',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='fourth_down_conversions',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='third_down_attempts',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='third_down_conversions',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
