# Generated by Django 5.2.17 on 2026-08-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_nflteamgamestats_defensive_qb_hits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='defensive_passing_yards_allowed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='defensive_qb_hits',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='defensive_rushing_yards_allowed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='defensive_sacks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='defensive_tackles_for_loss',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='defensive_turnovers_forced',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='field_goals_attempted',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='field_goals_made',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='offensive_passing_yards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='offensive_rushing_yards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='offensive_turnovers',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='passing_air_yards',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='passing_attempts',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='passing_completions',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='passing_cpoe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='passing_epa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='passing_yards_after_catch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='penalties',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='penalty_yards',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='points_allowed',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='points_for',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='rushing_attempts',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='rushing_epa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nflteamgamestats',
            name='sacks_allowed',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
