# Generated by Django 5.2.17 on 2026-08-21 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_start_time'),
        ('stats', '0003_alter_nflteamgamestats_defensive_passing_yards_allowed_and_more'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFLTeamProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_offense_strength', models.FloatField(blank=True, null=True)),
                ('rush_offense_strength', models.FloatField(blank=True, null=True)),
                ('pass_defense_strength', models.FloatField(blank=True, null=True)),
                ('rush_defense_strength', models.FloatField(blank=True, null=True)),
                ('offense_type', models.CharField(blank=True, choices=[('pass', 'Pass'), ('rush', 'Rush'), ('balanced', 'Balanced')], max_length=20, null=True)),
                ('defense_type', models.CharField(blank=True, choices=[('pass', 'Pass'), ('rush', 'Rush'), ('balanced', 'Balanced')], max_length=20, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfl_team_profiles', to='games.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfl_profiles', to='teams.team')),
                ('through_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfl_team_profiles', to='games.week')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('team', 'season', 'through_week'), name='unique_nfl_team_profile_per_week')],
            },
        ),
    ]
