# Generated by Django 5.2.17 on 2026-08-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_nflteamprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflteamgamestats',
            name='opponent_passing_attempts',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamgamestats',
            name='opponent_rushing_attempts',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
