# Generated by Django 5.2.17 on 2026-08-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_nflteamgamestats_opponent_passing_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflteamprofile',
            name='pass_defense_yards_per_attempt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='pass_defense_yards_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='pass_offense_epa_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='pass_offense_yards_per_attempt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='pass_offense_yards_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='rush_defense_yards_per_attempt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='rush_defense_yards_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='rush_offense_epa_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='rush_offense_yards_per_attempt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='rush_offense_yards_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
