# Generated by Django 5.2.17 on 2026-08-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_nflteamprofile_pass_defense_yards_per_attempt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nflteamprofile',
            old_name='pass_defense_strength',
            new_name='pass_defense_yards_per_attempt_strength',
        ),
        migrations.RenameField(
            model_name='nflteamprofile',
            old_name='pass_offense_strength',
            new_name='pass_defense_yards_per_game_strength',
        ),
        migrations.RenameField(
            model_name='nflteamprofile',
            old_name='rush_defense_strength',
            new_name='pass_offense_epa_per_game_strength',
        ),
        migrations.RenameField(
            model_name='nflteamprofile',
            old_name='rush_offense_strength',
            new_name='pass_offense_yards_per_attempt_strength',
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='pass_offense_yards_per_game_strength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='rush_defense_yards_per_attempt_strength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='rush_defense_yards_per_game_strength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='rush_offense_epa_per_game_strength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='rush_offense_yards_per_attempt_strength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='rush_offense_yards_per_game_strength',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
