# Generated by Django 5.2.17 on 2026-08-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_rename_pass_defense_strength_nflteamprofile_pass_defense_yards_per_attempt_strength_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflteamprofile',
            name='defensive_turnovers_forced_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='offensive_turnovers_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='point_differential_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='points_allowed_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='points_for_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='turnover_differential_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
