# Generated by Django 5.2.17 on 2026-08-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_nflteamprofile_defensive_turnovers_forced_per_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflteamprofile',
            name='defensive_qb_hits_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='defensive_sacks_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='defensive_tackles_for_loss_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='field_goal_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='field_goals_made_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='first_downs_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='fourth_down_conversion_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='opponent_pass_attempts_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='opponent_rush_attempts_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='pass_air_yards_per_attempt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='pass_attempts_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='pass_completion_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='pass_cpoe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='pass_epa_per_attempt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='pass_yards_after_catch_per_completion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='penalties_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='penalty_yards_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='rush_attempts_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='rush_epa_per_attempt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='sacks_allowed_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nflteamprofile',
            name='third_down_conversion_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
