# Generated by Django 5.2.17 on 2026-08-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='phase',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='series_game_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
