# Generated by Django 5.2.17 on 2026-08-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_phase_game_series_game_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_synced_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
