# Generated by Django 5.2.17 on 2026-08-20 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0002_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFLPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('QB', 'Quarterback'), ('RB', 'Running Back'), ('FB', 'Fullback'), ('WR', 'Wide Receiver'), ('TE', 'Tight End'), ('OL', 'Offensive Line'), ('OT', 'Offensive Tackle'), ('OG', 'Offensive Guard'), ('C', 'Center'), ('DL', 'Defensive Line'), ('DE', 'Defensive End'), ('DT', 'Defensive Tackle'), ('NT', 'Nose Tackle'), ('LB', 'Linebacker'), ('ILB', 'Inside Linebacker'), ('OLB', 'Outside Linebacker'), ('DB', 'Defensive Back'), ('CB', 'Cornerback'), ('S', 'Safety'), ('FS', 'Free Safety'), ('SS', 'Strong Safety'), ('K', 'Kicker'), ('P', 'Punter'), ('LS', 'Long Snapper')], max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NFLGamePlayerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('questionable', 'Questionable'), ('doubtful', 'Doubtful'), ('out', 'Out'), ('ir', 'Injured Reserve')], max_length=20)),
                ('expected_to_start', models.BooleanField(default=False)),
                ('captured_at', models.DateTimeField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_statuses', to='games.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_game_statuses', to='teams.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_statuses', to='players.nflplayer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game', 'player', 'captured_at'), name='unique_nfl_player_status_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='NFLPlayerGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passing_attempts', models.PositiveSmallIntegerField(default=0)),
                ('passing_completions', models.PositiveSmallIntegerField(default=0)),
                ('passing_yards', models.IntegerField(default=0)),
                ('passing_touchdowns', models.PositiveSmallIntegerField(default=0)),
                ('interceptions', models.PositiveSmallIntegerField(default=0)),
                ('rushing_attempts', models.PositiveSmallIntegerField(default=0)),
                ('rushing_yards', models.IntegerField(default=0)),
                ('rushing_touchdowns', models.PositiveSmallIntegerField(default=0)),
                ('targets', models.PositiveSmallIntegerField(default=0)),
                ('receptions', models.PositiveSmallIntegerField(default=0)),
                ('receiving_yards', models.IntegerField(default=0)),
                ('receiving_touchdowns', models.PositiveSmallIntegerField(default=0)),
                ('field_goal_attempts', models.PositiveSmallIntegerField(default=0)),
                ('field_goals_made', models.PositiveSmallIntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfl_player_stats', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfl_game_stats', to='players.nflplayer')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfl_player_game_stats', to='teams.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game', 'player'), name='unique_nfl_player_stats_per_game')],
            },
        ),
        migrations.CreateModel(
            name='NFLPlayerRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('QB', 'Quarterback'), ('RB', 'Running Back'), ('FB', 'Fullback'), ('WR', 'Wide Receiver'), ('TE', 'Tight End'), ('OL', 'Offensive Line'), ('OT', 'Offensive Tackle'), ('OG', 'Offensive Guard'), ('C', 'Center'), ('DL', 'Defensive Line'), ('DE', 'Defensive End'), ('DT', 'Defensive Tackle'), ('NT', 'Nose Tackle'), ('LB', 'Linebacker'), ('ILB', 'Inside Linebacker'), ('OLB', 'Outside Linebacker'), ('DB', 'Defensive Back'), ('CB', 'Cornerback'), ('S', 'Safety'), ('FS', 'Free Safety'), ('SS', 'Strong Safety'), ('K', 'Kicker'), ('P', 'Punter'), ('LS', 'Long Snapper')], max_length=10)),
                ('rank', models.PositiveSmallIntegerField()),
                ('score', models.FloatField()),
                ('captured_at', models.DateTimeField()),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=50)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='players.nflplayer')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfl_player_rankings', to='games.season')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'season', 'captured_at', 'model_name', 'model_version'), name='unique_nfl_player_ranking_snapshot')],
            },
        ),
    ]
