# Generated by Django 5.2.17 on 2026-08-20 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFLPlayerRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('QB', 'Quarterback'), ('RB', 'Running Back'), ('FB', 'Fullback'), ('WR', 'Wide Receiver'), ('TE', 'Tight End'), ('OL', 'Offensive Line'), ('OT', 'Offensive Tackle'), ('OG', 'Offensive Guard'), ('C', 'Center'), ('DL', 'Defensive Line'), ('DE', 'Defensive End'), ('DT', 'Defensive Tackle'), ('NT', 'Nose Tackle'), ('LB', 'Linebacker'), ('ILB', 'Inside Linebacker'), ('OLB', 'Outside Linebacker'), ('DB', 'Defensive Back'), ('CB', 'Cornerback'), ('S', 'Safety'), ('FS', 'Free Safety'), ('SS', 'Strong Safety'), ('K', 'Kicker'), ('P', 'Punter'), ('LS', 'Long Snapper')], max_length=10)),
                ('rank', models.PositiveSmallIntegerField()),
                ('score', models.FloatField()),
                ('captured_at', models.DateTimeField()),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=50)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='players.nflplayer')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfl_player_rankings', to='games.season')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'season', 'captured_at', 'model_name', 'model_version'), name='unique_nfl_player_ranking_snapshot')],
            },
        ),
    ]
