# Generated by Django 5.2.17 on 2026-08-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
