# Generated by Django 5.2.17 on 2026-09-07 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0005_alter_game_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sportsbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SportsbookRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('fee_rate', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('sportsbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='betting.sportsbook')),
            ],
        ),
        migrations.CreateModel(
            name='SportsbookFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_fixture_id', models.CharField(blank=True, max_length=255, null=True)),
                ('event_url', models.URLField(blank=True, max_length=500, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sportsbook_fixtures', to='games.game')),
                ('sportsbook_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='betting.sportsbookregion')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalGameMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('oddspapi', 'OddsPapi')], max_length=50)),
                ('external_fixture_id', models.CharField(max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_mappings', to='games.game')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_fixture_id'), name='unique_external_fixture'), models.UniqueConstraint(fields=('game', 'provider'), name='unique_game_provider')],
            },
        ),
        migrations.CreateModel(
            name='OddsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_type', models.CharField(choices=[('moneyline', 'Moneyline'), ('spread', 'Spread'), ('total', 'Total')], max_length=20)),
                ('side', models.CharField(choices=[('home', 'Home'), ('away', 'Away'), ('over', 'Over'), ('under', 'Under')], max_length=20)),
                ('line', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('decimal_odds', models.DecimalField(decimal_places=4, max_digits=8)),
                ('american_odds', models.IntegerField(blank=True, null=True)),
                ('external_market_id', models.CharField(max_length=100)),
                ('external_outcome_id', models.CharField(max_length=100)),
                ('betslip_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('source_changed_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('sportsbook_fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds_snapshots', to='betting.sportsbookfixture')),
            ],
            options={
                'indexes': [models.Index(fields=['sportsbook_fixture', 'market_type', 'side', '-source_changed_at'], name='odds_latest_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('sportsbook_fixture', 'external_market_id', 'external_outcome_id', 'source_changed_at'), name='unique_odds_snapshot')],
            },
        ),
        migrations.AddConstraint(
            model_name='sportsbookregion',
            constraint=models.UniqueConstraint(fields=('sportsbook', 'country_code'), name='unique_sportsbook_region'),
        ),
        migrations.AddConstraint(
            model_name='sportsbookfixture',
            constraint=models.UniqueConstraint(fields=('game', 'sportsbook_region'), name='unique_game_sportsbook_region'),
        ),
    ]
