# Generated by Django 5.2.17 on 2026-09-14 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTeamMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('oddspapi', 'OddsPapi')], max_length=50)),
                ('external_team_id', models.CharField(max_length=255)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_mappings', to='teams.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_team_id'), name='unique_external_team'), models.UniqueConstraint(fields=('team', 'provider'), name='unique_team_provider')],
            },
        ),
    ]
