# Generated by Django 5.2.17 on 2026-09-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_externalteammapping'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='externalteammapping',
            name='unique_team_provider',
        ),
    ]
