load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "config",
    srcs = [
        "__init__.py",
        "asgi.py",
        "settings.py",
        "urls.py",
        "wsgi.py",
    ],
    imports = [".."],
    visibility = ["//src:__subpackages__"],
    deps = ["@pip//django"],
)
