load("@rules_python//python:defs.bzl", "py_binary", "py_library")

# gazelle:python_root
load("//:pytest.bzl", "pytest_test")

exports_files(
    ["pytest_main.py"],
    visibility = ["//src:__subpackages__"],
)

py_binary(
    name = "manage",
    srcs = ["manage.py"],
    visibility = ["//src:__subpackages__"],
    deps = [
        "//src/betting",  # keep
        "//src/config",  # keep
        "//src/fantasy",  # keep
        "//src/games",  # keep
        "//src/ingestion",  # keep
        "//src/players",  # keep
        "//src/predictions",  # keep
        "//src/stats",  # keep
        "//src/teams",  # keep
        "@pip//django",
        "@pip//psycopg",  # keep
    ],
)

py_library(
    name = "src",
    srcs = [
        "manage.py",
        "pytest_main.py",
    ],
    visibility = ["//src:__subpackages__"],
    deps = [
        "@pip//django",
        "@pip//pytest",
    ],
)

py_binary(
    name = "pytest_main",
    srcs = ["pytest_main.py"],
    visibility = ["//src:__subpackages__"],
    deps = ["@pip//pytest"],
)
