load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "betting",
    srcs = [
        "__init__.py",
        "admin.py",
        "apps.py",
        "models.py",
        "tests.py",
        "views.py",
    ],
    imports = [".."],
    visibility = ["//src:__subpackages__"],
    deps = ["@pip//django"],
)
