load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "ingestion",
    srcs = [
        "__init__.py",
        "admin.py",
        "apps.py",
        "models.py",
        "results.py",
        "services.py",
        "state.py",
        "tests.py",
        "views.py",
    ],
    imports = [".."],
    visibility = ["//src:__subpackages__"],
    deps = [
        "//src/games",
        "//src/teams",
        "@pip//django",
    ],
)
