# Generated by Django 5.2.17 on 2026-08-21 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0005_alter_game_start_time'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(choices=[('teams', 'Teams'), ('games', 'Games'), ('team_stats', 'Team Stats')], max_length=50)),
                ('last_completed_at', models.DateTimeField(blank=True, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_states', to='teams.league')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_states', to='games.season')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('league', 'season', 'dataset'), name='unique_ingestion_state')],
            },
        ),
    ]
